title: Aicha A Toulba # your name (or website title) here
logo: "/attachment/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <h2>Data Analyst </h2>
  <a href="https://www.linkedin.com/in/aicha-ahmed-toulba/" target="_blank"><img height="25" src="https://img.shields.io/badge/-LinkedIn-%230077B5?style=for-the-badge&logo=linkedin&logoColor=white" target="_blank"></a>
  <a href="https://github.com/AishaAhmedToulba" target="_blank"><img height="26" src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" target="_blank"></a>
theme: jekyll-theme-minimal
